// convention = VERB + NOUN + STATUS

// UI
export const TOGGLE_UI = 'TOGGLE_UI'

// Errors
export const PRINT_ERROR = 'PRINT_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// User
export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

// Product
export const UPLOAD_TO_S3_REQUEST = 'UPLOAD_TO_S3_REQUEST'
export const UPLOAD_TO_S3_SUCCESS = 'UPLOAD_TO_S3_SUCCESS'
export const UPLOAD_TO_S3_FAILURE = 'UPLOAD_TO_S3_FAILURE'

export const UPLOAD_PRODUCT_REQUEST = 'UPLOAD_PRODUCT_REQUEST'
export const UPLOAD_PRODUCT_SUCCESS = 'UPLOAD_PRODUCT_SUCCESS'
export const UPLOAD_PRODUCT_FAILURE = 'UPLOAD_PRODUCT_FAILURE'

export const GET_PRODUCT_CATEGORIES_REQUEST = 'GET_PRODUCT_CATEGORIES_REQUEST'
export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS'
export const GET_PRODUCT_CATEGORIES_FAILURE = 'GET_PRODUCT_CATEGORIES_FAILURE'
