// convention = VERB + ADJECTIVE + NOUN + STATUS
// e.g. GET + INITIAL + PRODUCTS + REQUEST

// UI
export const TOGGLE_UI = 'TOGGLE_UI'
export const REDIRECT = 'REDIRECT'

// Errors
export const PRINT_ERROR = 'PRINT_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// Successes
export const PRINT_SUCCESS = 'PRINT_SUCCESS'
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS'

// Addresses
export const GET_ADDRESSES_REQUEST = 'GET_ADDRESSES_REQUEST'
export const GET_ADDRESSES_SUCCESS = 'GET_ADDRESSES_SUCCESS'
export const GET_ADDRESSES_FAILURE = 'GET_ADDRESSES_FAILURE'

export const CREATE_ADDRESS_REQUEST = 'CREATE_ADDRESS_REQUEST'
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS'
export const CREATE_ADDRESS_FAILURE = 'CREATE_ADDRESS_FAILURE'

export const UPDATE_ADDRESS_REQUEST = 'UPDATE_ADDRESS_REQUEST'
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS'
export const UPDATE_ADDRESS_FAILURE = 'UPDATE_ADDRESS_FAILURE'

export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST'
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS'
export const DELETE_ADDRESS_FAILURE = 'DELETE_ADDRESS_FAILURE'

// Feed
export const GET_INITIAL_FEED_REQUEST = 'GET_INITIAL_FEED_REQUEST'
export const GET_INITIAL_FEED_SUCCESS = 'GET_INITIAL_FEED_SUCCESS'
export const GET_INITIAL_FEED_FAILURE = 'GET_INITIAL_FEED_FAILURE'

export const GET_MORE_FEED_REQUEST = 'GET_MORE_FEED_REQUEST'
export const GET_MORE_FEED_SUCCESS = 'GET_MORE_FEED_SUCCESS'
export const GET_MORE_FEED_FAILURE = 'GET_MORE_FEED_FAILURE'

export const RESET_SEARCH_RESULTS = 'RESET_SEARCH_RESULTS'

// Feed
export const GET_INITIAL_SEARCH_RESULTS_REQUEST =
  'GET_INITIAL_SEARCH_RESULTS_REQUEST'
export const GET_INITIAL_SEARCH_RESULTS_SUCCESS =
  'GET_INITIAL_SEARCH_RESULTS_SUCCESS'
export const GET_INITIAL_SEARCH_RESULTS_FAILURE =
  'GET_INITIAL_SEARCH_RESULTS_FAILURE'

export const GET_MORE_SEARCH_RESULTS_REQUEST = 'GET_MORE_SEARCH_RESULTS_REQUEST'
export const GET_MORE_SEARCH_RESULTS_SUCCESS = 'GET_MORE_SEARCH_RESULTS_SUCCESS'
export const GET_MORE_SEARCH_RESULTS_FAILURE = 'GET_MORE_SEARCH_RESULTS_FAILURE'

// Payment
export const GET_STRIPE_TOKEN_REQUEST = 'GET_STRIPE_TOKEN_REQUEST'
export const GET_STRIPE_TOKEN_SUCCESS = 'GET_STRIPE_TOKEN_SUCCESS'
export const GET_STRIPE_TOKEN_FAILURE = 'GET_STRIPE_TOKEN_FAILURE'

export const BUY_PRODUCT_REQUEST = 'BUY_PRODUCT_REQUEST'
export const BUY_PRODUCT_SUCCESS = 'BUY_PRODUCT_SUCCESS'
export const BUY_PRODUCT_FAILURE = 'BUY_PRODUCT_FAILURE'

export const ADD_PRODUCT_TO_ORDER_CONFIRMED = 'ADD_PRODUCT_TO_ORDER_CONFIRMED'

// Store
export const GET_STORE_INFO_REQUEST = 'GET_STORE_INFO_REQUEST'
export const GET_STORE_INFO_SUCCESS = 'GET_STORE_INFO_SUCCESS'
export const GET_STORE_INFO_FAILURE = 'GET_STORE_INFO_FAILURE'

export const GET_INITIAL_STORE_PRODUCTS_REQUEST =
  'GET_INITIAL_STORE_PRODUCTS_REQUEST'
export const GET_INITIAL_STORE_PRODUCTS_SUCCESS =
  'GET_INITIAL_STORE_PRODUCTS_SUCCESS'
export const GET_INITIAL_STORE_PRODUCTS_FAILURE =
  'GET_INITIAL_STORE_PRODUCTS_FAILURE'

export const GET_MORE_STORE_PRODUCTS_REQUEST = 'GET_MORE_STORE_PRODUCTS_REQUEST'
export const GET_MORE_STORE_PRODUCTS_SUCCESS = 'GET_MORE_STORE_PRODUCTS_SUCCESS'
export const GET_MORE_STORE_PRODUCTS_FAILURE = 'GET_MORE_STORE_PRODUCTS_FAILURE'

// Product
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE'

export const UPLOAD_TO_S3_REQUEST = 'UPLOAD_TO_S3_REQUEST'
export const UPLOAD_TO_S3_SUCCESS = 'UPLOAD_TO_S3_SUCCESS'
export const UPLOAD_TO_S3_FAILURE = 'UPLOAD_TO_S3_FAILURE'

export const UPLOAD_PRODUCT_REQUEST = 'UPLOAD_PRODUCT_REQUEST'
export const UPLOAD_PRODUCT_SUCCESS = 'UPLOAD_PRODUCT_SUCCESS'
export const UPLOAD_PRODUCT_FAILURE = 'UPLOAD_PRODUCT_FAILURE'

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE'

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE'

export const GET_PRODUCT_CATEGORIES_REQUEST = 'GET_PRODUCT_CATEGORIES_REQUEST'
export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS'
export const GET_PRODUCT_CATEGORIES_FAILURE = 'GET_PRODUCT_CATEGORIES_FAILURE'

// Likes
export const GET_PRODUCT_LIKES_REQUEST = 'GET_PRODUCT_LIKES_REQUEST'
export const GET_PRODUCT_LIKES_SUCCESS = 'GET_PRODUCT_LIKES_SUCCESS'
export const GET_PRODUCT_LIKES_FAILURE = 'GET_PRODUCT_LIKES_FAILURE'

export const ADD_PRODUCT_LIKE_REQUEST = 'ADD_PRODUCT_LIKE_REQUEST'
export const ADD_PRODUCT_LIKE_SUCCESS = 'ADD_PRODUCT_LIKE_SUCCESS'
export const ADD_PRODUCT_LIKE_FAILURE = 'ADD_PRODUCT_LIKE_FAILURE'

export const DELETE_PRODUCT_LIKE_REQUEST = 'DELETE_LIKE_REQUEST'
export const DELETE_PRODUCT_LIKE_SUCCESS = 'DELETE_LIKE_SUCCESS'
export const DELETE_PRODUCT_LIKE_FAILURE = 'DELETE_LIKE_FAILURE'

// Messages
export const GET_MESSAGE_THREADS_REQUEST = 'GET_MESSAGE_THREADS_REQUEST'
export const GET_MESSAGE_THREADS_SUCCESS = 'GET_MESSAGE_THREADS_SUCCESS'
export const GET_MESSAGE_THREADS_FAILURE = 'GET_MESSAGE_THREADS_FAILURE'

export const GET_MESSAGE_THREAD_REQUEST = 'GET_MESSAGE_THREAD_REQUEST'
export const GET_MESSAGE_THREAD_SUCCESS = 'GET_MESSAGE_THREAD_SUCCESS'
export const GET_MESSAGE_THREAD_FAILURE = 'GET_MESSAGE_THREAD_FAILURE'

export const CREATE_MESSAGE_THREAD_REQUEST = 'CREATE_MESSAGE_THREAD_REQUEST'
export const CREATE_MESSAGE_THREAD_SUCCESS = 'CREATE_MESSAGE_THREAD_SUCCESS'
export const CREATE_MESSAGE_THREAD_FAILURE = 'CREATE_MESSAGE_THREAD_FAILURE'

export const CREATE_MESSAGE_REQUEST = 'CREATE_MESSAGE_REQUEST'
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS'
export const CREATE_MESSAGE_FAILURE = 'CREATE_MESSAGE_FAILURE'

// User
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const AUTHENTICATE_REQUEST = 'AUTHENTICATE_REQUEST'
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS'
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const GET_USERNAME_AVAILABILITY_REQUEST =
  'GET_USERNAME_AVAILABILITY_REQUEST'
export const GET_USERNAME_AVAILABILITY_SUCCESS =
  'GET_USERNAME_AVAILABILITY_SUCCESS'
export const GET_USERNAME_AVAILABILITY_FAILURE =
  'GET_USERNAME_AVAILABILITY_FAILURE'

export const LOGOUT_USER = 'LOGOUT_USER'
