// convention = VERB + NOUN + STATUS

// UI
export const TOGGLE_UI = "TOGGLE_UI"
export const REDIRECT = "REDIRECT"

// Errors
export const PRINT_ERROR = "PRINT_ERROR"
export const CLEAR_ERROR = "CLEAR_ERROR"

// Successes
export const PRINT_SUCCESS = "PRINT_SUCCESS"
export const CLEAR_SUCCESS = "CLEAR_SUCCESS"

// Feed
export const GET_FEED_REQUEST = "GET_FEED_REQUEST"
export const GET_FEED_SUCCESS = "GET_FEED_SUCCESS"
export const GET_FEED_FAILURE = "GET_FEED_FAILURE"

// Store
export const GET_STORE_INFO_REQUEST = "GET_STORE_INFO_REQUEST"
export const GET_STORE_INFO_SUCCESS = "GET_STORE_INFO_SUCCESS"
export const GET_STORE_INFO_FAILURE = "GET_STORE_INFO_FAILURE"

export const GET_STORE_PRODUCTS_REQUEST = "GET_STORE_PRODUCTS_REQUEST"
export const GET_STORE_PRODUCTS_SUCCESS = "GET_STORE_PRODUCTS_SUCCESS"
export const GET_STORE_PRODUCTS_FAILURE = "GET_STORE_PRODUCTS_FAILURE"

// Product
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE"

export const UPLOAD_TO_S3_REQUEST = "UPLOAD_TO_S3_REQUEST"
export const UPLOAD_TO_S3_SUCCESS = "UPLOAD_TO_S3_SUCCESS"
export const UPLOAD_TO_S3_FAILURE = "UPLOAD_TO_S3_FAILURE"

export const UPLOAD_PRODUCT_REQUEST = "UPLOAD_PRODUCT_REQUEST"
export const UPLOAD_PRODUCT_SUCCESS = "UPLOAD_PRODUCT_SUCCESS"
export const UPLOAD_PRODUCT_FAILURE = "UPLOAD_PRODUCT_FAILURE"

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE"

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE"

export const GET_PRODUCT_CATEGORIES_REQUEST = "GET_PRODUCT_CATEGORIES_REQUEST"
export const GET_PRODUCT_CATEGORIES_SUCCESS = "GET_PRODUCT_CATEGORIES_SUCCESS"
export const GET_PRODUCT_CATEGORIES_FAILURE = "GET_PRODUCT_CATEGORIES_FAILURE"

// Payment
export const GET_PAYMENT_TOKEN_REQUEST = "GET_PAYMENT_TOKEN_REQUEST"
export const GET_PAYMENT_TOKEN_SUCCESS = "GET_PAYMENT_TOKEN_SUCCESS"
export const GET_PAYMENT_TOKEN_FAILURE = "GET_PAYMENT_TOKEN_FAILURE"

export const ADD_CARD_TO_CUSTOMER_REQUEST = "ADD_CARD_TO_CUSTOMER_REQUEST"
export const ADD_CARD_TO_CUSTOMER_SUCCESS = "ADD_CARD_TO_CUSTOMER_SUCCESS"
export const ADD_CARD_TO_CUSTOMER_FAILURE = "ADD_CARD_TO_CUSTOMER_FAILURE"

export const CREATE_TRANSACTION_REQUEST = "CREATE_TRANSACTION_REQUEST"
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS"
export const CREATE_TRANSACTION_FAILURE = "CREATE_TRANSACTION_FAILURE"

// Orders
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE"

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAILURE = "GET_ORDER_FAILURE"

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST"
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS"
export const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE"

// User
export const AUTH_FB_WITH_BE_REQUEST = "AUTH_FB_WITH_BE_REQUEST"
export const AUTH_FB_WITH_BE_SUCCESS = "AUTH_FB_WITH_BE_SUCCESS"
export const AUTH_FB_WITH_BE_FAILURE = "AUTH_FB_WITH_BE_FAILURE"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE"

export const CREATE_CUSTOMER_REQUEST = "CREATE_CUSTOMER_REQUEST"
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS"
export const CREATE_CUSTOMER_FAILURE = "CREATE_CUSTOMER_FAILURE"

export const GET_USERNAME_AVAILABILITY_REQUEST =
  "GET_USERNAME_AVAILABILITY_REQUEST"
export const GET_USERNAME_AVAILABILITY_SUCCESS =
  "GET_USERNAME_AVAILABILITY_SUCCESS"
export const GET_USERNAME_AVAILABILITY_FAILURE =
  "GET_USERNAME_AVAILABILITY_FAILURE"

export const LOGOUT_USER = "LOGOUT_USER"
